### ISSUE TITLE
544 and 365 error in Domoticz.

### ISSUE THREAD

**Issue by jvrrr** [addiejanssen/domoticz-solaredge-modbustcp-plugin#44]
### Discussed in https://github.com/addiejanssen/domoticz-solaredge-modbustcp-plugin/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **jvrrr** October 20, 2022</sup>
Hi..,

I have some issues with this plugin in Domoticz.
I get this error, I can't resolve . 
Can You please help me out:

![image](https://user-images.githubusercontent.com/63355527/197039730-339f9d9b-53d2-4ab1-b2c4-9e90f1cbf04f.png)
</div>

**Comment by addiejanssen** [comment]
Closing the issue; discussion will continue in the discussions section.
