### ISSUE TITLE
New ModBus Python or Solaredge doesn't work

### ISSUE THREAD

**Issue by diegoflyer** [addiejanssen/domoticz-solaredge-modbustcp-plugin#9]
I have already the plugin running with pymodbus 2.4.0, I tried a fresh install and the plugin was not able to connect with inverter (pymodbus 2.5.0).
I try to change the folder dist-packages with the old installation and started to work correctly......

**Comment by divx118** [comment]
Yes thanks for the heads up.
I solved it with:
```
sudo pip3 uninstall pymodbus
sudo pip3 install pymodbus==2.4.0
```
